### ISSUE TITLE
Background doesn't extend to edges of the screen

### ISSUE THREAD

**Issue by edgarss** [neetrath/NBHQ_Survey01#1]
![Simulator Screen Shot - iPhone 11 Pro - 2021-03-01 at 10 01 15](https://user-images.githubusercontent.com/9453323/109446911-25456800-7a75-11eb-9ff9-f1469ae0e87b.png)

On iPhone 11 Pro the background doesn't extend to top and bottom edges and leaves write spaces there.

**Comment by neetrath** [comment]
Fixed. 27e52dc
