### ISSUE TITLE
VIPER module set up

### ISSUE THREAD

**Issue by edgarss** [neetrath/NBHQ_Survey01#3]
I would recomend looking at the compact template in our Nimble VIPER templates repo https://github.com/nimblehq/VIPER-Templates#viper-module-template-compact

By using a module to connect the View, Presenter, Interactor, Router makes the code much cleaner than doing it all in HomeView.swift setup() function. With your current VIPER architecture the View has quite a lot of presentation and logic.

Also why is the filename for HomeViewController HomeView.swift? makes it sound like it is a UIView from the name

**Comment by neetrath** [comment]
I try to change the project structure to match with Nimble's structure. Based on this VIPER iOS Demo (https://github.com/nimblehq/viper-ios-demo).

Fixed. 541f079
